name: Publish new addon version

on:
  workflow_dispatch: null
  release:
    types: [created]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      # - run: npm test

  publish-addon:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: npx @wext/shipit chrome dist
        env:
          WEXT_SHIPIT_CHROME_EXTENSION_ID: ${{ secrets.WEXT_SHIPIT_CHROME_EXTENSION_ID }}
          WEXT_SHIPIT_CHROME_CLIENT_ID: ${{ secrets.WEXT_SHIPIT_CHROME_CLIENT_ID }}
          WEXT_SHIPIT_CHROME_CLIENT_SECRET: ${{ secrets.WEXT_SHIPIT_CHROME_CLIENT_SECRET }}
          WEXT_SHIPIT_CHROME_REFRESH_TOKEN: ${{ secrets.WEXT_SHIPIT_CHROME_REFRESH_TOKEN }}